/*global systemDictionary:true */
"use strict";

systemDictionary = {
    "hoover adapter settings": {
        en: "Adapter settings for hoover",
        de: "Adaptereinstellungen für hoover",
        ru: "Настройки адаптера для hoover",
        pt: "Configurações do adaptador para hoover",
        nl: "Adapterinstellingen voor hoover",
        fr: "Paramètres d'adaptateur pour hoover",
        it: "Impostazioni dell'adattatore per hoover",
        es: "Ajustes del adaptador para hoover",
        pl: "Ustawienia adaptera dla hoover",
        "zh-cn": "hoover的适配器设置",
    },
    "App Email": {
        en: "App Email",
        de: "App-E-Mail",
        ru: "Электронная почта приложения",
        pt: "Email do aplicativo",
        nl: "App-e-mail",
        fr: "Courriel de l'application",
        it: "E-mail dell'app",
        es: "Correo electrónico de la aplicación",
        pl: "E-mail aplikacji",
        "zh-cn": "应用电子邮件",
    },
    "App Password": {
        en: "App Password",
        de: "App-Passwort",
        ru: "Пароль приложения",
        pt: "Senha de app",
        nl: "App-wachtwoord",
        fr: "Mot de passe de l'application",
        it: "Password dell'app",
        es: "Contraseña de la aplicación",
        pl: "Hasło do aplikacji",
        "zh-cn": "应用密码",
    },
    "Update interval (in minutes)": {
        en: "Update interval (in minutes)",
        de: "Aktualisierungsintervall (in Minuten)",
        ru: "Интервал обновления (в минутах)",
        pt: "Intervalo de atualização (em minutos)",
        nl: "Update-interval (in minuten)",
        fr: "Intervalle de mise à jour (en minutes)",
        it: "Intervallo di aggiornamento (in minuti)",
        es: "Intervalo de actualización (en minutos)",
        pl: "Interwał aktualizacji (w minutach)",
        "zh-cn": "更新间隔（分钟）",
    },
};
